# Generated by Django 5.0 on 2024-01-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('number_of_days', models.SmallIntegerField()),
                ('leave_type', models.CharField(max_length=25, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=12)),
                ('employee_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.faculty')),
            ],
        ),
    ]
