# Generated by Django 5.0 on 2024-01-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaves',
        ),
    ]
