# Generated by Django 5.0 on 2024-01-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.JSONField(),
        ),
    ]
