# Generated by Django 5.0 on 2024-01-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_leaves_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='applied_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
