# Generated by Django 5.0 on 2024-01-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_leaves_applied_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='applied_year',
            new_name='year',
        ),
    ]
