# Generated by Django 5.0 on 2024-01-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_delete_leaves'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Colleges',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
