# Generated by Django 5.0 on 2024-01-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='section_id',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
